version: "3"

services:
  dohproxy:
    image: dnsproxy:latest
    ports:
      - "53:53/udp"
    container_name: DoHProxy
    environment:
      - DNS_SERVER=192.168.18.4
    entrypoint: ["/app/scripts/run.sh"]
